name: Maven Build and Test

on:
  push:
    branches:
      - 'releases/**'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'corretto'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean verify

    - name: Check Test Results
      run: |
        if [ -f target/surefire-reports/*.xml ]; then
          echo "Test results found."
        else
          echo "No test results found. Failing the build."
          exit 1
        fi