name: Maven Build and Test

on:
  push:
    branches:
      - 'feature/**'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'corretto'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean verify

    - name: Check Test Results
      run: |
        if [ -f target/surefire-reports/*.xml ]; then
          echo "Test results found."
        else
          echo "No test results found. Failing the build."
        fi
        
  merge:
    needs: tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install GitHub CLI
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt-get update
        sudo apt-get install gh

    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Create Pull Request
      run: |
        git checkout -b auto-merge-branch
        git push origin auto-merge-branch
        gh pr create --base develop --head auto-merge-branch --title "Auto Merge to Develop" --body "Auto-generated pull request from successful tests."